### ISSUE TITLE
Auto conversion block doesn't drop

### ISSUE THREAD

**Issue by Anaerin** [MattDahEpic/AutoOreDictConvert1.8#23]
I can create and place the Auto Converter, but when I break it it just disappears. It should drop itself, like virtually every other Minecraft block. And some directions on how to use it (tooltip in JEI, for instance) would be real handy. I thought it was broken when I couldn't connect to it from the side.

Also, XNet will not connect to it, which makes automation using it a bit more difficult.

**Comment by MattDahEpic** [comment]
Could I get what version of AODC you're playing with?

**Comment by Anaerin** [comment]
16.1.8, so it says.

**Comment by MattDahEpic** [comment]
The drops and tooltip should be fixed in 16.1.9. I will investigate XNet more, but the block itself does not have an inventory and converts passively so it doesn't really expose anything XNet could use to automate with, just pump items in and pull them out.

Closing for now, thank you for the report!
