### ISSUE TITLE
Client crashes wen auto-converting quartz glass.

### ISSUE THREAD

**Issue by TiborKoderman** [MattDahEpic/AutoOreDictConvert1.8#9]
I have noticed that if you make quartz glass and put it into your inventory it automatically converts it to hardened glass, but the problem is that it can't choose which so it gives you a missing texture ittem, that if you hover over with a mouse it chrashes your client. The only way to fix this was to clear my inventory and then make hard glass using obsidian and lead.

**Comment by MattDahEpic** [comment]
If you're running AODC in a pack, you'll need to contact the pack makers since they set up the configuration wrong. Otherwise, what is your version and what are the config entires you have set up.

AODC gives exactly what you told it to give, so I'd love to double check your configs to figure out if there is indeed an issue here
